---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/martinlindner/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_files:
  - .gitconfig
  - .gitignore

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - awscli
  - aws-shell
  - fish
  - git
  - go
  - nmap
  - tmux
  - terraform

homebrew_taps:
  - buo/cask-upgrade
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - google-chrome
  - google-cloud-sdk
  - insomnia
  - iterm2
  - slack
  - the-unarchiver
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - vmware-remote-console
  - homebrew/cask-fonts/font-fira-mono-for-powerline
  - homebrew/cask-fonts/font-inconsolata-for-powerline
  - homebrew/cask-fonts/font-noto-mono-for-powerline


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1295203466, name: "Microsoft Remote Desktop 10" }
  - { id: 405399194, name: "Kindle" }
  - { id: 784801555, name: "Microsoft OneNote" }

mas_email: "mlindner@gaba.co.jp"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
